# Generated by Django 4.2 on 2023-04-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_reveiw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reveiw',
            name='task',
        ),
        migrations.AddField(
            model_name='image',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.slave'),
        ),
        migrations.AddField(
            model_name='image',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reveiw',
            name='mark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reveiw',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.image'),
        ),
    ]
