# Generated by Django 4.2 on 2023-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.TextField(max_length=30),
        ),
    ]
